FORMAT: 1A

# Array API

Example of array definition in `MSON`.

# Data Structures

## Post1

Array as an object field.

+ text (string, required) - post text
+ comments (array[string]) - comments list

## Post2

Array of objects as an object field.

+ text (string, required) - post text
+ comments (array) - comments list
    + (object)
        + id (number, required)
        + text (string, required)

## Post3

Array with elements of a named type.

+ text (string, required) - post text
+ comments (array[Comment]) - comments list

## Comment

+ id (number, required)
+ text (string, required)

## Comments (array[Comment])

Array as a base type for a named type.
