FORMAT: 1A

# Array API

Example of enums in `MSON`.

# Data Structures

## User

Enum as an object field.

+ name (string, required)
+ status (enum[string])
    + active - active user
    + inactive - inactive user

## UserStatus (enum[string])

Enum as a base for a named type.

+ active - active user
+ inactive - inactive user
