FORMAT: 1A

# Array API

Демонстрация объявления enum в `MSON`

# Data Structures

## User

Объявление enum как поля объекта

+ name (string, required)
+ status (enum[string])
    + active - активный
    + inactive - неактивный

## UserStatus (enum[string])

Объявление enum как именованный тип

+ active - активный
+ inactive - неактивный
