FORMAT: 1A

# Inheritance API

Демонстрация наследования одного типа от другого

# Data Structures

## User

Базовый тип

+ name (string, required)
+ email (string, required)

## Admin (User)

Тип-наследник

+ permissions (array[string])
