FORMAT: 1A

# Inheritance API

Example of inheritance of one type from another type.

# Data Structures

## User

Base type

+ name (string, required)
+ email (string, required)

## Admin (User)

Extended type

+ permissions (array[string])
