FORMAT: 1A

# Validations API

Example of value validations

# Data Structures

## MSISDN (number, minimum="79000000000", maximum="79999999999")

## Coords (array[number], min-length="2", max-length="2")

## Email (string, format="email")

## Ticket (string, pattern="^[A-Z]+-\\d+$")
