# Group User resources

## Comments [/comments]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)

### POST

+ Request (application/json)

    + Body

          {
            "text": "My comment"
          }

+ Response 204

## Notes [/notes]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)

### POST

+ Request (application/json)

    + Body

          {
            "text": "Test note"
          }

+ Response 204
