FORMAT: 1A

# Resource and Actions API

Example of how to declare multiple [Action](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-action-section) sections in a [Resource](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-resource-section) section.

# /message

`Resource` section is defined by a URI template and can contain one or more `Action` sections.
URI template should start with `/`.

## GET

`Action` section which is included in `Resource` section is defined by an HTTP method and should contain at least one `Response` section.
This `Response` section defines the format of server responses. Every response should include an HTTP status code and may contain a payload.

+ Response 200 (text/plain)

    + Body

          Hello world!

## PUT

Another `Action` section defines a `PUT /message` request.
Additionally to `Response`, `Action` section may contain one or more `Request` sections that define data transmitted to a server.

+ Request (application/json)

    + Body

          {
            "text": "Test message"
          }

+ Response 200
