FORMAT: 1A

# Resource and Actions API

Example of declaring multiple [Action](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-action-section) sections inside of a named [Resource](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-resource-section) section.

# Message of the day [/message]

A `Resource` section may have a name (identifier). A well-chosen name will help the reader better understand the purpose of a particular resource.

## Update message of the day [PUT]

You can give a name to an `Action` section too.

+ Request (application/json)

    + Body

          {
            "text": "Test message"
          }

+ Response 200

## GET

If the purpose of an `Action` is clear, you can omit the name.

+ Response 200 (text/plain)

    + Body

          Hello world!
