FORMAT: 1A

# Grouping Resources API

Демонстрация возможности группировки ресурсов.

# Group ресурсы пользователя

В некоторых случаях может потребоваться группировка нескольких ресурсов для улучшения читаемости
документации. Для реализации этой возможности в API Blueprint имеется секция
[Group](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-resourcegroup-section).

## Комментарии [/comments]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)

### POST

+ Request (application/json)

    + Body

          {
            "text": "My comment"
          }

+ Response 204

## Заметки [/notes]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)

### POST

+ Request (application/json)

    + Body

          {
            "text": "Test note"
          }

+ Response 204

# Group ресурсы администратора

## Пользователи [/users]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)
