FORMAT: 1A

# Grouping Resources API

Example of resource grouping.

# Group User resources

In some cases, you may need to group multiple resources for better readability.
To provide such functionality API Blueprint specification defines [Group](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-resourcegroup-section) section.

## Comments [/comments]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)

### POST

+ Request (application/json)

    + Body

          {
            "text": "My comment"
          }

+ Response 204

## Notes [/notes]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)

### POST

+ Request (application/json)

    + Body

          {
            "text": "Test note"
          }

+ Response 204

# Group Administrator resources

## Users [/users]

### GET

+ Response 200 (application/json)
    + Attributes (array, required)
