FORMAT: 1A

# Responses API

Example of multiple ways to define a response.

Every resource should include at least one response.
You can define a response with the [Response](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-response-section) section.

## GET /message

+ Response 200 (text/plain)

    Plain text response with headers

    + Headers

            X-My-Message-Header: 42

    + Body

            Hello World!

+ Response 200 (application/json)
    Response with MSON data structure
    + Attributes (object)
        + foo: `bar` (string, required)

+ Response 403
    Response without a body
