FORMAT: 1A

# Requests API

Example of multiple ways to define a request.

You can define a request with the [Request](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-request-section) section.
Requests have the same internal structure as [Responses](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-response-section).

## POST /message

+ Request (text/plain)

    Plain text request with headers

    + Headers

            X-My-Message-Header: 42

    + Body

            Hello World!

+ Request (application/json)
    Request with MSON data structure
    + Attributes (object)
        + foo: `bar` (string, required)

+ Response 200
