FORMAT: 1A

# Parameters API

Example of multiple ways to define a URI parameter.

You need to specify parameters in a URI and describe them in a [Parameters](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-uriparameters-section) section.

:::warning
Please be warned that syntax to describe parameters may resemble MSON, but it has differences:
you are not allowed to use objects, named types, and arrays of non-primitive elements to describe parameters.
:::

## GET /messages/{id}

Given resource specifies parameter `id` as [URI Template variable](http://tools.ietf.org/html/rfc6570).
The name of the parameter is defined in curly braces. Example of the URI: `/messages/10`.

+ Parameters
  + id: 1 (number) - unique message identifier

+ Response 200

## GET /messages{?search}

Given resource specifies query parameter `search`.
Example of the URI: `/messages?search=hello`

+ Parameters
  + search: hello (string) - show only messages that contain the search string

+ Response 200
