FORMAT: 1A

# Attributes API

Демонстрация задания структуры ответа с помощью секции
[Attributes](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section).

При описании запросов и ответов можно использовать не только статические данные
секции `Body`, но и описать структуру данных с помощью языка
[MSON](https://github.com/funbox/mson) в секции `Attributes`.

## GET /messages

+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + type (enum, required)
                + incoming - входящее сообщение
                + outcoming - исходящее сообщение
            + `author_id` (number, required) - идентификатор автора сообщения
            + text: `Hello world` (string, required) - текст сообщения
            + tags (array[string], optional) - теги сообщения
