FORMAT: 1A

# Attributes API

Example of defining response structure with the [Attributes](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section) section.

You can use a static `Body` section in requests and responses or you can define a data structure in `Attributes` section
using [MSON](https://github.com/funbox/mson) language.

## GET /messages

+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + type (enum, required)
                + incoming - incoming message
                + outgoing - outgoing message
            + `author_id` (number, required) - identifier of the author
            + text: `Hello world` (string, required) - message text
            + tags (array[string], optional) - message tags
