FORMAT: 1A

# Data Structures API

Демонстрация создания переиспользуемых структур данных с помощью секции
[Data Structures](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-data-structures)
и последующего использования этих структур при описании ответов.

# Data Structures

# MessageType(enum)

+ incoming - входящее сообщение
+ outcoming - исходящее сообщение

# Tag

+ id: 42 (number, required) - идентификатор тега
+ title: `some tag` (string, required) - текст тега

# Message

+ type (MessageType, required)
+ `author_id` (number, required) - идентификатор автора сообщения
+ text: `Hello world` (string, required) - текст сообщения
+ tags (array[Tag], optional) - теги сообщения

## GET /messages

+ Response 200 (application/json)
    + Attributes (array[Message])
