FORMAT: 1A

# Resource Prototypes API

Example of how to define a set of reusable responses with the [Resource Prototypes](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-resource-prototypes) section and use them in documentation.

# Resource Prototypes

## UserResource

+ Response 403 (application/json)
    + Attributes
        + status: `permission denied` (string, required, fixed)

+ Response 404 (application/json)
    + Attributes
        + status: `not found` (string, required, fixed)

# Group User resources (UserResource)

Each resource in the group includes two responses that are defined in the `UserResource` prototype.

## Comments [/comments]

### GET

+ Response 200 (application/json)
    + Attributes (array)

### POST

+ Request (application/json)

    + Body

          {
            "text": "My comment"
          }

+ Response 204

## Notes [/notes]

### GET

+ Response 200 (application/json)
    + Attributes (array)

### POST

+ Request (application/json)

    + Body

          {
            "text": "Test note"
          }

+ Response 204
