FORMAT: 1A

# Schema Structures API

Example of how to define a set of reusable data structures using [Schema Structures](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-schema-structures)
sections and use them in documentation.

# Schema Structures

# MSISDN

MSON lacks some of the features that are available in JSON Schema, so sometimes it's easier to describe some of the data structures directly in JSON Schema.
To do that, create a named type in the `Schema Structures` section as you do with named types in a `Data Structures` section.

When you define a named type, you need to specify JSON Schema in the `Schema` section and an example with data in `Body` section.
Data in `Body` section will be used to generate examples in requests and responses. Both sections are required.

Named Schema types cannot inherit from other Schema types and cannot be used as a parent structure to other Schema types.
These types may be used as object fields or array elements.

+ Schema

            {
              "type": "number",
              "minimum": 79000000000,
              "maximum": 79999999999,
              "multipleOf": 1.0
            }
+ Body

            79000000123

# Data Structures

# User

Schema type `MSISDN` is used as a field type of the User named type.

+ name: `John` (string, required) - user name
+ msisdn (MSISDN, required) - user phone

## GET /users

+ Response 200 (application/json)
    + Attributes (array[User])
