FORMAT: 1A

# Imports API

Example of how to split large document into separate smaller files using keyword [Import](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-import).

# Import ./imports/user-resources.apib
# Import ./imports/admin-resources.apib
