FORMAT: 1A

# Imports API
Демонстрация разбиения большой документации на несколько файлов с помощью инструкции
[Import](https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-import)
и последующего использования этих структур при описании ответов.

# Import ./imports/user-resources.apib
# Import ./imports/admin-resources.apib
